repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-toml
  - id: pretty-format-json
    args: [ --autofix ]
  - id: check-added-large-files
  - id: check-ast

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.1
  hooks:
  - id: ruff
    args: [ --fix ]
    types_or: [ python, jupyter ]

- repo: https://github.com/psf/black
  rev: 24.4.1
  hooks:
  - id: black
  - id: black-jupyter
